### ISSUE TITLE
対象がLock状態の場合にOpenのみがトリガーされて、以降進捗を解除するまで機能しない

### ISSUE THREAD

**Issue by nea-c** [Ai-Akaishi/CloseDetector#2]
再現手順
1. Lockされたチェスト等を用意
1. 素手、または開くことのできないアイテムを持ってそのブロックを開こうとする

**Comment by Ai-Akaishi** [comment]
ご報告ありがとうございます。
Lock時の処理修正および検知機能を追加しました。
