### ISSUE TITLE
#on_locked、#on_openedの先でclear等すると以降機能しなくなる時がある

### ISSUE THREAD

**Issue by nea-c** [Ai-Akaishi/CloseDetector#3]
#on_locked、#on_openedを呼び出す前にインベントリを記録しているためかと考えていますが、
clearで発生しているのか、真の原因は特定できていません

lock報告時同様進捗を剥奪するまで動作しません

※マルチ環境で一部の人にしか発生しなかったため、申し訳ありませんが再現手順はわかりません

対応何卒よろしくお願いいたします

**Comment by Ai-Akaishi** [comment]
各イベントハンドラ内でインベントリ操作系コマンドを実行しても問題なく動作するよう修正いたしました。
ご報告ありがとうございました。
